# Generated by Django 6.0.1 on 2026-02-02 20:46
# Re-running this migration to ensure superuser is created.

import os
from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from decouple import config

def create_superuser_and_update_site(apps, schema_editor):
    """
    This function will be run by the migration to programmatically
    create a superuser and update the site domain.
    """
    User = get_user_model()
    
    # Get superuser details from environment variables
    ADMIN_USERNAME = config('ADMIN_USERNAME', default=None)
    ADMIN_PASSWORD = config('ADMIN_PASSWORD', default=None)

    # Only proceed if all environment variables are set
    if ADMIN_USERNAME and ADMIN_PASSWORD:
        # Check if the superuser already exists
        if not User.objects.filter(username=ADMIN_USERNAME).exists():
            print(f"Creating superuser: {ADMIN_USERNAME}")
            User.objects.create_superuser(
                username=ADMIN_USERNAME,
                password=ADMIN_PASSWORD
            )
        else:
            print(f"Superuser {ADMIN_USERNAME} already exists.")

    # Update the site domain
    # This ensures QR codes are generated with the correct production URL.
    try:
        site = Site.objects.get(pk=1)
        render_hostname = config('RENDER_EXTERNAL_HOSTNAME', default=None)
        if render_hostname and site.domain == 'example.com':
            print(f"Updating site domain to: {render_hostname}")
            site.domain = render_hostname
            site.name = render_hostname
            site.save()
        else:
            print("Site domain already configured or RENDER_EXTERNAL_HOSTNAME not set.")
    except Site.DoesNotExist:
        print("Default site not found. Skipping domain update.")


class Migration(migrations.Migration):

    dependencies = [
        # This migration depends on the initial creation of users and sites
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(create_superuser_and_update_site),
    ]
