# Generated by Django 6.0.1 on 2026-01-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for your product for easy identification.', max_length=200)),
                ('text_description', models.TextField(help_text='The full text description that will be read aloud.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('public_url', models.URLField(blank=True)),
                ('linked_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='products.product')),
            ],
        ),
    ]
