# Generated by Django 6.0.1 on 2026-02-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(help_text='Use [blank][placeholder] to create dynamic fields.'),
        ),
    ]
