# Generated by Django 6.0.1 on 2026-02-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_template_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image_data',
            field=models.TextField(blank=True, help_text='Base64 encoded image data of the QR code.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='A descriptive name for the product.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_description',
            field=models.TextField(help_text='The text that will be read aloud when the QR code is scanned.'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(help_text='Use [placeholder] to create dynamic fields.'),
        ),
    ]
